#myName = input("What's your name?: ")
#myAge = input("How old are you?: ")
#print("Gee, that's REALLY OLD")
#replit = input("Do you like Replit?: ")
#print("OF COURSE YOU DO!")

#print(myName)
#print(myAge)

print ("****************************************************************")
print("Getting to Know you! \n")
myName1 = input("What's your name? ")
myFood = input("What's your favourite food? ")
myMusic = input("What's your favourite music? ")
myLoc = input("Where do you live? ")
print()
print("You are\n", myName1)
print("You're probably hungry for\n", myFood)
print("and you're definitely getting your groove on to\n", myMusic)
print("living in the amazing\n", myLoc)
